service: notification-service

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 256
  region: eu-west-3
  stage: ${opt:stage, 'dev'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action: ses:SendEmail
          Resource: arn:aws:ses:*
        - Effect: Allow
          Action:
            - sqs:ReceiveMessage
          Resource: ${self:custom.mailQueue.arn}

resources:
  Resources:
    MailQueue: ${file(resources/MailQueue.yml):MailQueue}
  Outputs:
    MailQueueArn: ${file(resources/MailQueue.yml):Outputs.MailQueueArn}
    MailQueueUrl: ${file(resources/MailQueue.yml):Outputs.MailQueueUrl}

functions:
  sendMail:
    handler: src/handlers/sendMail.handler
    events:
      - sqs:
          arn: ${self:custom.mailQueue.arn}
          enabled: true
          batchSize: 1

custom:
  mailQueue:
    name: MailQueue-${self:provider.stage}
    #arn: !GetAtt MailQueue.Arn
    arn:
      Fn::GetAtt: [MailQueue, Arn]
    url: !Ref MailQueue